version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: nozorin_api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./api/.env.local
    environment:
      - DB_HOST=db
      - REDISHOST=redis
      - SOCKET_SERVICE_URL=http://nozorin_realtime:3002
    depends_on:
      - db
      - redis
      - realtime

  realtime:
    build:
      context: .
      dockerfile: socket/Dockerfile
    container_name: nozorin_realtime
    ports:
      - "3002:3002"
    volumes:
      - ./socket:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./socket/.env.local
    environment:
      - REDISHOST=redis
      - DB_HOST=db
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: nozorin_db
    restart: always
    environment:
      MYSQL_DATABASE: nozorin_db
      MYSQL_USER: nozorin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: nozorin_redis
    restart: unless-stopped
    env_file:
      - ./api/.env.local
    command: sh -c "redis-server --requirepass $${REDISPASSWORD}"
    ports:
      - "6380:6379"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: nozorin_ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./ui/.env.local
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:3002
    depends_on:
      - api
      - realtime

volumes:
  mysql_data:
