version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: nozorin_api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
    command: npm run dev
    env_file:
      - ./api/.env.local
    environment:
      - DB_HOST=db
      - REDISHOST=redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: nozorin_db
    restart: always
    environment:
      MYSQL_DATABASE: nozorin_db
      MYSQL_USER: nozorin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: nozorin_redis
    restart: unless-stopped
    env_file:
      - ./api/.env.local
    command: sh -c "redis-server --requirepass $${REDISPASSWORD}"
    ports:
      - "6380:6379"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: nozorin_ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    command: npm run dev
    env_file:
      - ./ui/.env.local
    environment:
      - PORT=3000

volumes:
  mysql_data:
